### ISSUE TITLE
lint /test/*.* also please

### ISSUE THREAD

**Issue by tomByrer** [mozilla-neutrino/neutrino-dev#857] opened 2018-05-08 14:39 UTC
Procedure: Set up new library project:

```JSON
    "@neutrinojs/jest": "^8.2.3",
    "@neutrinojs/library": "^8.2.3",
    "@neutrinojs/standardjs": "^8.2.3",
    "neutrino": "^8.2.3"
  ```

The `/src/index.js` was linted with `neutrino lint --fix` (eg semicolon dropped), but `/test/simple_test.js` was ignored.  I don't want the tester writing the scripts be left out on the linting party!

**Comment by eliperelman** [comment] 2018-05-08 14:47
Duplicate of #331. I will respond over there. Thanks for the issue!

**Closed by eliperelman** 2018-05-08 14:47 UTC
