### ISSUE TITLE
TypeError: Cannot read property 'addQmark' of undefined when attempting to create a project

### ISSUE THREAD

**Issue by p-jaya** [mozilla-neutrino/neutrino-dev#968] opened 2018-06-27 04:18 UTC
### Bug

When attempting to create a new project, I receive this error:

`TypeError: Cannot read property 'addQmark' of undefined when attempting to create a project`

- What version of Neutrino are you using?
  @neutrinojs/create-project@8.2.3
- Are you trying to use any presets? If so, which ones, and what versions?
  * A web or Node.js application
  * Preact
  * Jest
  * Airbnb style rules
- Are you using the Yarn client or the npm client? What version?
  Tried these versions:
  * npm v6.1.0
  * npm v5.6.0
  * yarn v1.7.0
- What version of Node.js are you using?
  Tried these versions:
  * v9.11.2
  * v10.5.0
- What operating system are you using?
   macOS
- What did you do?
  Attempted to create a project by executing either:
  * `yarn create @neutrinojs/project <directory-name>`
  * `npx @neutrinojs/create-project <directory-name>`
- What did you expect to happen?
  Project would be created
- What actually happened, contrary to your expectations?
  An error is thrown.  Here's the console output:

```
Welcome to Neutrino! 👋
To help you create your new project, I am going to ask you a few questions.

? 🤔  First up, what would you like to create? A web or Node.js application
? 🤔  Next, what kind of application would you like to create? Preact
? 🤔  Would you like to add a test runner to your project? Jest
? 🤔  Would you like to add linting to your project? Airbnb style rules

👌  Looks like I have all the info I need. Give me a moment while I create your project!

   create test/package.json
events.js:165
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'addQmark' of undefined
    at Compiler.<anonymous> (/Users/my-user/.config/yarn/global/node_modules/nanomatch/lib/compilers.js:92:16)
    at Compiler.visit (/Users/my-user/.config/yarn/global/node_modules/snapdragon/lib/compiler.js:129:15)
    at Compiler.mapVisit (/Users/my-user/.config/yarn/global/node_modules/snapdragon/lib/compiler.js:143:12)
    at Compiler.compile (/Users/my-user/.config/yarn/global/node_modules/snapdragon/lib/compiler.js:168:10)
    at Snapdragon.compile (/Users/my-user/.config/yarn/global/node_modules/snapdragon/index.js:156:32)
    at /Users/my-user/.config/yarn/global/node_modules/micromatch/index.js:786:23
    at memoize (/Users/my-user/.config/yarn/global/node_modules/micromatch/index.js:859:13)
    at Function.micromatch.compile (/Users/my-user/.config/yarn/global/node_modules/micromatch/index.js:783:10)
    at create (/Users/my-user/.config/yarn/global/node_modules/micromatch/index.js:686:25)
    at /Users/my-user/.config/yarn/global/node_modules/micromatch/index.js:695:16
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/my-user/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:406:18)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)```

**Comment by jwulf** [comment] 2018-06-27 05:00
I'm getting this error when running jest with 23.2.0 in our build system.

**Comment by jonschlinkert** [comment] 2018-06-27 06:40
This bug was right after it happened. Just reinstall to get the fix. See https://github.com/micromatch/nanomatch/issues/15 for more info.

**Comment by edmorley** [comment] 2018-06-27 10:19
Hi! Thank you for filing this issue. 

As @jonschlinkert spotted above, this was due to a regression in a new nanomatch patch release that is pulled in via yeoman-generator -> micromatch -> caret range dependency on nanomatch. The nanomatch release has since been unpublished (micromatch/nanomatch#15), plus micromatch also opened a PR to stop using a caret range dependency (micromatch/micromatch#131; though presuming that won't be merged now).

Testing locally shows the nanomatch unpublish has fixed the issue.

**Closed by edmorley** 2018-06-27 10:19 UTC

**Comment by p-jaya** [comment] 2018-06-27 16:17
Fixed while I slept; amazing.  Tried it today and worked well.  Thanks!
