### ISSUE TITLE
Support webpack-dev-server v4

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-neutrino/neutrino-dev#1700] opened 2022-02-14 17:56 UTC
### Bug or issue?

Please try to answer the following questions:

- What version of Neutrino are you using? 9.5.0
- Are you trying to use any presets? If so, which ones, and what versions?
- Are you using the Yarn client or the npm client? What version? 1.22.5
- What version of Node.js are you using? 16.13.2
- What operating system are you using? Linux
- What did you do? Upgraded the `webpack-dev-server` package [from v3 to v4](https://github.com/mozilla/treeherder/commit/389c4ee0273792de2477f604e2118e4e7b834a31) https://github.com/mozilla/treeherder
- What did you expect to happen? No issue
- What actually happened, contrary to your expectations? Several failures to launch the frontend container because manual migrations were necessary, including for neutrino (see [bug 1755334](https://bugzilla.mozilla.org/show_bug.cgi?id=1755334))

[Webpack v4 migration guide](https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md)

Modification necessary:
* [packages/dev-server/index.js](https://github.com/neutrinojs/neutrino/blob/560b7b618c9856f26914de34c4109bd75722c374/packages/dev-server/index.js#L12)
  * `stats` as attribute of a `devMiddleware` attribute
  * `overlay` as attribute of `client` attribute

There are other files which also use these attributes.

**Comment by edmorley** [comment] 2022-02-14 18:05
Hi! 

This is expected, since Neutrino does not yet support webpack 5 (see #1624 and #1584).

The Neutrino docs say to use webpack-dev-server v3, eg:
https://neutrinojs.org/packages/web/#requirements

And the packages have `webpack-dev-server` v3 in `peerDependencies`:
https://github.com/neutrinojs/neutrino/blob/70822185e107b8e465a62b1eed74d6f62a559ed7/packages/web/package.json#L48

...so an error will be shown during npm/yarn install if a different version is used.

I would recommend adding `yarn check` (or whatever yarn v2+ / npm equivalent exists) to your CI pipeline, so unmet peer dependencies cause CI to fail, to make it clearer when incompatible versions are being used.

I'm going to close this out since everything is working as designed (wrt docs and declared dependencies), and the webpack 5 work is already being tracked in #1624. However, it's worth noting that I don't use this project any more, and unless someone else steps up to maintain it, it's unlikely that it will see many/any more releases.

**Comment by edmorley** [comment] 2022-02-14 18:07
Actually, I see `webpack-dev-server` v4 supports webpack v4 too (and not only webpack v5), so the work to support `webpack-dev-server` v4 needn't be coupled with the webpack 5 work. As such, I've reopened this and changed the title to reflect it's for adding support.

**Comment by edmorley** [comment] 2024-02-03 19:49
Closing since unfortunately this project is no longer maintained. See:
https://github.com/neutrinojs/neutrino/issues/1707
https://github.com/neutrinojs/webpack-chain/issues/358

**Closed as not planned by edmorley** 2024-02-03 19:49 UTC
