### ISSUE TITLE
file included in config.html.scripts does not copy correctly

### ISSUE THREAD

**Issue by gasolin** [mozilla-neutrino/neutrino-dev#42] opened 2017-02-22 16:11 UTC
I ported my homepage to based on neutrino-preset-react , and defined several css/scripts via `config.html.scripts` entry point in `package.json`

https://github.com/gasolin/gasolin.github.io/blob/source/package.json#L48

Though css works nicely, js file is not copied correctly.

**Comment by eliperelman** [comment] 2017-02-22 16:55
So it looks like the HTML file generation works correctly, but the assets don't make it into the build directory. This is caused by the copy plugin in the web preset:

https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-web/src/index.js#L223-L225

It specifically doesn't copy JS files because it expects those to be included through the app building process. There are a few ways to tackle this.

### Add to vendor chunk

I believe you could add these items to the vendor chunk and they will make it into your build:

```json
{
  "config": {
    "neutrino": {
      "entry": {
        "vendor": [
          "react",
          "react-dom",
          "./src/static/js/redirect.js",
          "./src/static/js/pushmenu.js"
        ]
      }
    }
  }
}
```

### Import in entry point

This puts it in the `index` chunk:

```js
import './static/js/pushmenu';
import './static/js/ga.js';
```

### Override copy plugin

You could also either override the copy plugin to remove the restriction on certain JS files, or to also copy over the static directory, something like (not tested):

```js
module.exports = ({ config }) => {
  config
    .plugin('copy')
    .inject((Plugin, [patterns, options]) => {
      options.ignore = ['!static/**/*.js*'];
      return new Plugin(patterns, options);
    });
};
```

**Comment by eliperelman** [comment] 2017-02-26 00:24
Closing, since this is working as intended. Please reopen if you feel like those solutions won't work.

**Closed by eliperelman** 2017-02-26 00:24 UTC

**Comment by gasolin** [comment] 2017-03-05 06:10
defime vendor seems work in my case, thanks
