### ISSUE TITLE
require('neutrino')

### ISSUE THREAD

**Issue by aretecode** [mozilla-neutrino/neutrino-dev#151] opened 2017-03-28 05:59 UTC
<img width="951" alt="screen shot 2017-03-27 at 10 06 06 pm" src="https://cloud.githubusercontent.com/assets/4022631/24390951/e93d1078-1340-11e7-8070-4749755da799.png">

Was working to require it and use it programatically until updating from beta.1 -> 5.0.1

**Comment by skogsmaskin** [comment] 2017-03-28 09:54
@aretecode I think you have to ``const {Neutrino} = require('neutrino')``

**Comment by eliperelman** [comment] 2017-03-28 13:33
Can you post your usage of the API?

**Comment by eliperelman** [comment] 2017-03-28 20:45
So, I can confirm this issue. The problem is not `require`ing Neutrino, it is `console.log`ging the exports which causes the issue:

```js
console.log(require('neutrino'));
```

:boom:

Since the export of the Neutrino is an object with an inspect method:

```js
{
  inspect()
}
```

Node.js will automatically call the `inspect` method of an object when logging it to the console. Since it doesn't pass the expected args, it blows up.

Workaround: don't console.log the `require('neutrino')` default export. Log either individual functions or destructure what you need.

**Comment by aretecode** [comment] 2017-03-28 22:48
https://github.com/mozilla-neutrino/neutrino-dev/pull/152

**Comment by eliperelman** [comment] 2017-03-28 23:44
Fixed in #152.

**Closed by eliperelman** 2017-03-28 23:44 UTC
